config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users, except: [:new]
  resources :articles
  resources :categories, except: [:destroy]

  get 'pages/home', to: 'pages#home'
  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'

  root to: 'pages#home'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories , through: :article_categories
  validates :title , presence: true, length: {minimum:3, maximum:50}
  validates :description , presence: true, length: {minimum:10, maximum:300}
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def index
    @articles = Article.all.order("created_at DESC")
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def show
  end

  def new
    @article = Article.new
  end

 
  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

      if @article.save
        redirect_to article_path(@article), notice: 'Article was successfully created.'
      else
        render 'new' 
      end
      
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article), notice: 'Article was successfully updated.' 
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end


    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
  <div class="well well-lg">
    <div class="article-title">
      <%= link_to  article.title.capitalize, article %>
    </div>
    <div class="article-body">
      <%= truncate(article.description.capitalize, length: 100) %>
      <div class="article-meta-details">
        <small>Created by: <%= article.user.username  if article.user %>,
                         <%= time_ago_in_words(article.created_at) %> ago
                         last updated: <%= time_ago_in_words(article.updated_at) %> ago </small>
      </div>
    </div>
    <% if article.categories.any? %>
        <p>Categories: <%= render article.categories  %></p>
    <% end %>
    <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
      <div class="article-actions">
        <%= link_to 'Edit this article', edit_article_path(article), class:"btn btn-xs btn-primary" %>
        <%= link_to "Delete this article",  article_path(article), method: :delete,
                    data: { confirm: "Are you sure you want to delete this article?"},
                    class:"btn btn-xs btn-danger" %>
      </div>
      <% end %>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, :html => {class: "form-horizontal", role: "form"}) do |form| %>
 <%= render 'shared/errors', obj: @article %>

  <div class="row">
    <div class="col-md-12">

    <div class="form-group">
      <div class="control-label col-sm-2">
        <h4><%= form.label :title %></h4>
      </div>
      <div class="col-sm-8">
      <%= form.text_field :title, class:"form-control", placeholder: "Title of Article", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <h4><%= form.label :description %></h4>
      </div>
      <div class="col-sm-8">
      <%= form.text_area :description, rows:10, class:"form-control", placeholder: "Description of Article", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
         <div class="col-sm-offset-2 col-sm-8">
          <%= form.collection_check_boxes :category_ids , Category.all, :id, :name do |cb| %>
           <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class:"btn btn-primary btn-lg"%>
      </div>
    </div>
  <% end %>

    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to articles listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Hackathon all Articles</h1>

<div align="center">
  <%= will_paginate @articles  %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate @articles %>
</div>
 

app/views/articles/new.html.erb
<h1 align="center">New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h2 align="center">Title:<%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by: </li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user)%></li>
          <li class="article-title">
            <%= link_to @article.user.username.capitalize, user_path(@article.user)%>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
          </small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any?  %>
      <p>
          Categories: <%= render @article.categories %>
      </p>
  <% end   %>

  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Edit this article', edit_article_path(@article), class:"btn btn-xs btn-primary" %>
      <%= link_to "Delete this article",  article_path(@article), method: :delete,
                                          data: { confirm: "Are you sure you want to delete this article?"},
                                          class:"btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to 'View all articles', articles_path, class:"btn btn-xs btn-success" %>
  </div>
</div>